start_date: "2015-01-01"
end_date: "2024-12-31"
cond_len: 60
seq_len: 10
target_fields: ["log_return", "volume", "turnover", "high", "low", "EMA_20", "EMA_50", "RSI_14", "MACD"]
target_dim: 9
cond_input_dim: 9
cond_dim: 32
time_embed_dim: 32
hidden_dim: 64
T_diffusion: 100
lr: 0.001
weight_decay: 0.0001
n_epochs: 8000
volatility: 0.5
use_dynamic_beta: true
s_base: 0.008
alpha: 1.0
use_compound_poisson: true
jump_intensity: 0.05
jump_scale: 1.0
ddim_steps: 50
eta: 0.1